project:
  type: website
  output-dir: docs

website:
  title: "Michael Weylandt"
  description: 
    Michael Weylandt's Research Website
  site-url: "https://michael-weylandt.com/"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: "./index.html"
      - text: "Research"
        href: "./research.html"
      - text: "Publications"
        href: "./publications.html"
      - text: "Teaching"
        href: "./teaching.html"
      - text: "Software"
        href: "./software.html"
      - text: "About"
        href: "./about.html"
      - text: "Contact"
        href: "./contact.html"

format: 
  html:
    theme:
      - darkly
    toc: false
