#!/usr/bin/Rscript
library(rmarkdown)
library(distill)
for(f in list.files('publications', pattern = "Rmd")){
    file.copy(paste0("publications/", f), paste0("./publication_", f))
}
for(f in list.files('software', pattern = "Rmd")){
    file.copy(paste0("software/", f), paste0("./software_", f))
}
rmarkdown::render_site()
for(f in list.files('publications', pattern = "Rmd")){
    f_html <- gsub("Rmd", "html", f)
    f_Rmd_src  <- file.path("docs", paste0("publication_", f))
    f_html_src <- file.path("docs", paste0("publication_", f_html))
    f_html_dst <- file.path("docs", "publications", f_html)

    f_content <- readLines(f_html_src)
    f_content <- gsub("./", "../", f_content, fixed = TRUE)
    f_content <- gsub(".../", "../", f_content, fixed = TRUE)
    f_content <- gsub("site_libs", "../site_libs", f_content)

    writeLines(f_content, con = f_html_dst)

    unlink(f_html_src)
    unlink(f_Rmd_src)
    unlink(f)
}
for(f in list.files('software', pattern = "Rmd")){
    f_html <- gsub("Rmd", "html", f)
    f_Rmd_src  <- file.path("docs", paste0("software", f))
    f_html_src <- file.path("docs", paste0("software_", f_html))
    f_html_dst <- file.path("docs", "software", f_html)

    f_content <- readLines(f_html_src)
    f_content <- gsub("./", "../", f_content, fixed = TRUE)
    f_content <- gsub(".../", "../", f_content, fixed = TRUE)
    f_content <- gsub("site_libs", "../site_libs", f_content)

    writeLines(f_content, con = f_html_dst)

    unlink(f_html_src)
    unlink(f_Rmd_src)
    unlink(f)
}
unlink(list.files("docs", pattern = "Rmd", recursive = TRUE, full.names = TRUE))
unlink(list.files(pattern = "publication_"))
unlink(list.files(pattern = "software_"))

search_content <- readLines("docs/search.json")
search_content <- gsub("publication_", "publications/", search_content)
search_content <- gsub("software_", "software/", search_content)
writeLines(search_content, "docs/search.json")

sitemap_content <- readLines("docs/sitemap.xml")
sitemap_content <- gsub("publication_", "publications/", sitemap_content)
sitemap_content <- gsub("software_", "software/", sitemap_content)
writeLines(sitemap_content, "docs/sitemap.xml")
system("git add *")
