---
title: "Welcome!"
site: distill::distill_website
---

Hello and welcome to my website! My name is Michael Weylandt.
As of October 2022, I am a postdoctoral appointee in the
Statistical Sciences group at Sandia National Laboratories,
working J. Derek Tucker and Laura P. Swiler. Previously, I was
an US Intelligence Community Postdoctoral Research Fellow hosted
at the University of Florida Informatics Institute, where I was
advised by George Michailidis as well as two mentors from the
Intelligence Community. Before this, I earned my Ph.D. at Rice
University in 2020, worked in finance from 2013 to 2015,
and taught at Sherborne School in the UK from 2012 to 2013.
My research is in statistical machine learning, with a recent
interest on network data and in machine learning fairness. As Sandia,
I also work with large-scale computer experiments and climate statistics.
For a more formal bio, please see my [CV](assets/Weylandt_CV.pdf) and my
[About](about.html) page. More detail on my
[Publications](publications.html) and [Software](software.html) can be
found on those pages.
