---
title: "Welcome!"
---

Hello and welcome to my website! My name is Michael Weylandt.

I am a (tenure-track) Assistant Professor in the [Paul H. Chook Department of Information Systems and Statistics](https://zicklin.baruch.cuny.edu/faculty-research/academic-departments/information-technology-statistics/) in the [Zicklin School of Business](https://zicklin.baruch.cuny.edu/) at [Baruch College](https://baruch.cuny.edu/), [City University of New York (CUNY)](https://cuny.edu). My research is in statistical machine learning, with particular recent interests in climate statistics, network data, and machine learning fairness. Before joining Baruch, I was a Postdoctoral Appointee in the Statistical Sciences group at Sandia National Laboratories, working [J. Derek Tucker](https://research.tetonedge.net/) and [Laura P. Swiler](https://www.sandia.gov/ccr/staff/laura-painton-swiler/), and before that I was an US Intelligence Community Postdoctoral Research Fellow hosted at the University of Florida Informatics Institute, where I was advised by [George Michailidis](https://georgemichailidis.github.io/) as well as two mentors from the Intelligence Community. I earned my Ph.D. in Statistics at Rice University in 2020, worked in finance from 2013 to 2015, and taught at Sherborne School in the UK from 2012 to 2013. 

For a more formal bio, please see my [CV](assets/Weylandt_CV.pdf) and my
[About](about.html) page. More detail on my
[Publications](publications.html) and [Software](software.html) can be
found on those pages.
