---
title: "Debiasing Projections for Fair Principal Components Analysis"
description: "Submitted Conference Publication"
author:
  - name: Michael Weylandt
    url: https://michaelweylandt.github.io
    affiliation: UF Informatics Insitute
  - name: Genevera I. Allen
    url: https://genevera.rice.edu
    affiliation: Departments of Electrical & Computer Engineering, Computer Science, and Statistics, Rice University
output: distill::distill_article
---

**Abstract:** Machine learning models can often reflect or exacerbate societal biases present in training data.  While most attention in the nascent field of algorithmic fairness has focused on bias mitigation for supervised learning, biases can also be a problem for unsupervised analyses.  With Principal Components Analysis (PCA), for example, biased dimension reduction can affect downstream analysis as well as affect data exploration and modeling decisions.  In this paper, we propose a novel framework for Fair PCA that finds debiasing projections of the data, or projections that remove the effect from any protected attribute.  We show that our approach has many advantages over existing formulations of Fair PCA including a fast, closed form solution, generality and wide applicability to many protect attributes, and its ease of interpretation and usage like projections in classical PCA.  We demonstrate the bias mitigating advantages of our Fair PCA method compared to existing proposals for Fair PCA on several synthetic and benchmark datasets. 





