---
title: "Network Clustering for Latent State and Changepoint Detection"
description: "Submitted Conference Publication"
author:
  - name: Madeline Navarro
    affiliation: Department of Electrical & Computer Engineering, Rice University
  - name: Genevera I. Allen
    url: https://genevera.rice.edu
    affiliation: Departments of Electrical & Computer Engineering, Computer Science, and Statistics, Rice University
  - name: Michael Weylandt
    url: https://michaelweylandt.github.io
    affiliation: UF Informatics Insitute
output: distill::distill_article
---

Network models provide a powerful and flexible framework for analyzing a wide range of structured data sources. In many situations of interest, however, multiple networks can be constructed to capture different aspects of an underlying phenomenon or to capture changing behavior over time. In such settings, it is often useful to \emph{cluster} together related networks in attempt to identify patterns of common structure. In this paper, we propose a convex approach for the task of network clustering. Our approach uses a convex fusion penalty to induce a smoothly-varying tree-like cluster structure, eliminating the need to select the number of clusters \emph{a priori}. We provide an efficient algorithm for convex network clustering and demonstrate its effectiveness on synthetic examples. 





