---
title: "Dynamic Visualization and Fast Computation for Convex Clustering via Algorithmic Regularization"
description: "*Journal of Computational and Graphical Statistics* 29(1), pp. 87-96. 2020"
author:
  - name: Michael Weylandt
    url: https://michaelweylandt.github.io
    affiliation: Department of Statistics, Rice University
  - name: John Nagorski
    affiliation: Department of Statistics, Rice University
  - name: Genevera I. Allen
    url: https://genevera.rice.edu
    affiliation: Departments of Statistics, Electrical & Computer Engineering, and Computer Science, Rice University
output: distill::distill_article
---

Winner of the *ASA Section on Statistical Learning and Data Science (SLDS) 2019 Student Paper Competition*

**Abstract:** Convex clustering is a promising new approach to the classical problem of clustering, combining strong performance in empirical studies with rigorous theoretical foundations. Despite these advantages, convex clustering has not been widely adopted, due to its computationally intensive nature and its lack of compelling visualizations. To address these impediments, we introduce *Algorithmic Regularization*, an innovative technique for obtaining high-quality estimates of regularization paths using an iterative one-step approximation scheme. We justify our approach with a novel theoretical result, guaranteeing global convergence of the approximate path to the exact solution under easily-checked non-data-dependent assumptions. The application of algorithmic regularization to convex clustering yields the **C**onvex Clustering via **A**lgorithmic **R**egularization **P**aths (CARP) algorithm for computing the clustering solution path. On example data sets from genomics and text analysis, CARP delivers over a 100-fold speed-up over existing methods, while attaining a finer approximation grid than standard methods. Furthermore, CARP enables improved visualization of clustering solutions: the fine solution grid returned by CARP can be used to construct a convex clustering-based dendrogram, as well as forming the basis of a dynamic path-wise visualization based on modern web technologies. Our methods are implemented in the open-source **R** package **clustRviz**, available at https://github.com/DataSlingers/clustRviz.

**Publisher DOI:** [10.1080/10618600.2019.1629943](https://doi.org/10.1080/10618600.2019.1629943)

**PubMed:** [32982130](https://pubmed.ncbi.nlm.nih.gov/32982130/)

**Working Copy:** ArXiv [1901.01477](https://arxiv.org/abs/1901.01477)

<hr>

**Summary:** 

**Related Software:** The clustering methodology from this paper is implemented in my **R** package [**clustRviz**](../software/clustRviz.html). The algorithmic regularization scheme from this paper was applied to the Generalized ADMM from my paper on [co-clustering algorithms](coclustering_algs.html) to give the improved **CBASS** algorithm in the package.

<hr>

**Citation:**

```
@ARTICLE{Weylandt:2020,
  AUTHOR="Michael Weylandt and John Nagorski and Genevera I. Allen",
  TITLE="Dynamic Visualization and Fast Computation for Convex Clustering via Algorithmic Regularization",
  JOURNAL="Journal of Computational and Graphical Statistics",
  YEAR=2020,
  VOLUME=29,
  NUMBER=1,
  PAGES={87-96},
  DOI="10.1080/10618600.2019.1629943",
}
```
