---
title: "Beyond PCA: Additional Dimension Reduction Techniques to Consider in the Development of Climate Fingerprints"
description: "*Journal of Climate* 37(5), pp. 1723–1735. 2024"
author:
  - name: Michael Weylandt
    url: https://michael-weylandt.com/
    affiliation: Baruch College, CUNY
  - name: Laura P. Swiler
    affiliation: Center for Computing Research, Sandia National Laboratories
output: distill::distill_article
---

**Abstract:** Dimension reduction techniques are an essential part of the climate analyst’s toolkit. Due to the enormous scale of climate data, dimension reduction methods are used to identify major patterns of variability within climate dynamics, to create compelling and informative visualizations, and to quantify major named modes such as El Niño–Southern Oscillation. Principal components analysis (PCA), also known as the method of empirical orthogonal functions (EOFs), is the most commonly used form of dimension reduction, characterized by a remarkable confluence of attractive mathematical, statistical, and computational properties. Despite its ubiquity, PCA suffers from several difficulties relevant to climate science: high computational burden with large datasets, decreased statistical accuracy in high dimensions, and difficulties comparing across multiple datasets. In this paper, we introduce several variants of PCA that are likely to be of use in climate sciences and address these problems. Specifically, we introduce non-negative, sparse, and tensor PCA and demonstrate how each approach provides superior pattern recognition in climate data. We also discuss approaches to comparing PCA-family results within and across datasets in a domain-relevant manner. We demonstrate these approaches through an analysis of several runs of the E3SM climate model from 1991 to 1995, focusing on the simulated response to the Mt. Pinatubo eruption; our findings are consistent with a recently identified stratospheric warming fingerprint associated with this type of stratospheric aerosol injection.

**Publisher DOI:** [10.1175/JCLI-D-23-0267.1](https://doi.org/10.1175/JCLI-D-23-0267.1)

**Supporting Materials:** Supporting materials, including code necessary to reproduce our experiments, can be found at [10.5281/zenodo.10581709](https://doi.org/10.5281/zenodo.10581709)

<hr>

**Citation:**

```
@ARTICLE{Weylandt:2024-BeyondPCA,
  TITLE="Beyond PCA: Additional Dimension Reduction Techniques to Consider in the Development of Climate Fingerprints",
  AUTHOR="Michael Weylandt and Laura P. Swiler",
  JOURNAL="Journal of Climate",
  YEAR=2024,
  VOLUME=37,
  NUBER=5,
  DOI="10.1175/JCLI-D-23-0267.1",
  PAGES={1723–1735 }
}
```
