---
title: "Conditional multi-step attribution for climate forcings"
description: "Submitted article (under review)"
author:
  - name: Christopher R. Wentland
    affiliation: Sandia National Laboratories
  - name: Michael Weylandt
    url: https://michael-weylandt.com/
    affiliation: Baruch College, CUNY
  - name: Laura P. Swiler
    affiliation: Sandia National Laboratories
  - name: Thomas S. Ehrmann
    affiliation: Sandia National Laboratories
  - name: Diana Bull
    affiliation: Sandia National Laboratories
---

**Abstract:** Attribution of climate impacts to a source forcing is critical to understanding, communicating, and addressing the effects of human influence on the climate. While standard attribution methods, such as optimal fingerprinting, have been successfully applied to long-term, widespread effects such as global surface temperature warming, they often struggle in low signal-to-noise regimes, typical of short-term climate forcings or climate variables which are loosely related to the forcing. Single-step approaches, which directly relate a source forcing and final impact, are unable to utilize additional climate information to improve attribution certainty. To address this shortcoming, this paper presents a novel multi-step attribution approach which is capable of analyzing multiple variables conditionally. A connected series of climate effects are treated as dependent, and relationships found in intermediary steps of a causal pathway are leveraged to better characterize the forcing impact. This enables attribution of the forcing level responsible for the observed impacts, while equivalent single-step approaches fail. Utilizing a scalar feature describing the forcing impact, simple forcing response models, and a conditional Bayesian formulation, this method can incorporate several causal pathways to identify the correct forcing magnitude. As an exemplar of a short-term, high-variance forcing, we demonstrate this method for the 1991 eruption of Mt. Pinatubo. Results indicate that including stratospheric and surface temperature and radiative flux measurements increases attribution certainty compared to analyses derived solely from temperature measurements. This framework has potential to improve climate attribution assessments for both geoengineering projects and long-term climate change, for which standard attribution methods may fail. 

**Working Copy:** [ArXiv 2409.01396](https://arxiv.org/abs/2409.01396)

---

**Citation:**

```
@ARTICLE{Wentland:2024,
  AUTHOR="Christopher R. Wentland and Michael Weylandt and Laura P. Swiler and Thomas S. Ehrmann and Diana Bull",
  TITLE="Conditional multi-step attribution for climate forcings",
  YEAR=2024,
  DOI={10.48550/arXiv.2409.01396},
  JOURNAL="ArXiv Pre-Print 2409.01396"
}
```
